// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:5ed8be46-e437-437d-843e-23d7c0903f41",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_H0YhCn2n9",
    "aws_user_pools_web_client_id": "1i2p9ku54iqns30kclrmettbpf"
};


export default awsmobile;
